datetime_columns:
- tanggal
features:
- stasiun
- pm10
- pm25
- so2
- co
- o3
- no2
int32_columns:
- pm10
- pm25
- so2
- co
- o3
- no2
- max
label: categori
label_categories:
- BAIK
- SEDANG
- TIDAK SEHAT
label_categories_new:
- BAIK
- TIDAK BAIK
object_columns:
- stasiun
- critical
- categori
path_joined_data: ../data/interim/joined_dataset.pkl
path_raw_data: ../data/raw/
range_co:
- 0
- 100
range_no2:
- 0
- 100
range_o3:
- 0
- 140
range_pm10:
- 0
- 800
range_pm25:
- 0
- 400
range_so2:
- 0
- 500
range_stasiun:
- DKI1 (Bunderan HI)
- DKI2 (Kelapa Gading)
- DKI3 (Jagakarsa)
- DKI4 (Lubang Buaya)
- DKI5 (Kebon Jeruk) Jakarta Barat
